# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: nileshzarkar/accounts
  tag: s14

containerPort: 8080

h2:
    console:
      enabled
    
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

h2_console: true
appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: true